#### setting working directory ####
setwd("D:/Uni/Network Science/Progetto")

#### importing libraries ####
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(MASS)
require(gridExtra)

#### loading data ####
tweets_02 <- read_csv("2022-02/tweets_filtered.csv",col_types=cols(col_character(),col_character(),col_character(),col_character(),
                                                                   col_character(),col_character(),col_character(),col_character(),
                                                                   col_double(),col_character(),col_character(),col_double(),col_double())) %>% dplyr::select(-1)
tweets_06 <- read_csv("2022-06/tweets_filtered.csv",col_types=cols(col_character(),col_character(),col_character(),col_character(),
                                                                   col_character(),col_character(),col_character(),col_character(),
                                                                   col_double(),col_character(),col_character(),col_double(),col_double())) %>% dplyr::select(-1)
tweets_06 <- tweets_06[-c(13090,13091,13092),]
tweets_09 <- read_csv("2022-09/tweets_filtered.csv",col_types=cols(col_character(),col_character(),col_character(),col_character(),
                                                                   col_character(),col_character(),col_character(),col_character(),
                                                                   col_double(),col_character(),col_character(),col_double(),col_double())) %>% dplyr::select(-1)
tweets_12 <- read_csv("2022-12/tweets_filtered.csv",col_types=cols(col_character(),col_character(),col_character(),col_character(),
                                                                   col_character(),col_character(),col_character(),col_character(),
                                                                   col_double(),col_character(),col_character(),col_double(),col_double())) %>% dplyr::select(-1)

replies_02 <- read_csv("2022-02/replies_filtered.csv",col_types=cols(col_character(),col_character(),col_character(),col_character(),col_character(),
                                                                     col_character(),col_character(),col_character(),col_character(),
                                                                     col_double(),col_character(),col_character(),col_double(),col_double())) %>% dplyr::select(-1)
replies_06 <- read_csv("2022-06/replies_filtered.csv",col_types=cols(col_character(),col_character(),col_character(),col_character(),col_character(),
                                                                     col_character(),col_character(),col_character(),col_character(),
                                                                     col_double(),col_character(),col_character(),col_double(),col_double())) %>% dplyr::select(-1)
replies_09 <- read_csv("2022-09/replies_filtered.csv",col_types=cols(col_character(),col_character(),col_character(),col_character(),col_character(),
                                                                     col_character(),col_character(),col_character(),col_character(),
                                                                     col_double(),col_character(),col_character(),col_double(),col_double())) %>% dplyr::select(-1)
replies_12 <- read_csv("2022-12/replies_filtered.csv",col_types=cols(col_character(),col_character(),col_character(),col_character(),col_character(),
                                                                     col_character(),col_character(),col_character(),col_character(),
                                                                     col_double(),col_character(),col_character(),col_double(),col_double())) %>% dplyr::select(-1)

neigh_02 <- read_csv("2022-02/neigh.csv",col_types=cols(col_character(),col_character(),col_double(),col_double(),col_double())) %>% dplyr::select(-1) %>% drop_na()
neigh_06 <- read_csv("2022-06/neigh.csv",col_types=cols(col_character(),col_character(),col_double(),col_double(),col_double())) %>% dplyr::select(-1) %>% drop_na()
neigh_09 <- read_csv("2022-09/neigh.csv",col_types=cols(col_character(),col_character(),col_double(),col_double(),col_double())) %>% dplyr::select(-1) %>% drop_na()
neigh_12 <- read_csv("2022-12/neigh.csv",col_types=cols(col_character(),col_character(),col_double(),col_double(),col_double())) %>% dplyr::select(-1) %>% drop_na()

hashtags_02 <- read_csv("2022-02/hashtags/hashtaglist.csv", col_types = cols(col_character(),col_character(),col_double(),col_double(),col_double(),col_double()))
hashtags_06 <- read_csv("2022-06/hashtags/hashtaglist.csv", col_types = cols(col_character(),col_character(),col_double(),col_double(),col_double(),col_double()))
hashtags_09 <- read_csv("2022-09/hashtags/hashtaglist.csv", col_types = cols(col_character(),col_character(),col_double(),col_double(),col_double(),col_double()))
hashtags_12 <- read_csv("2022-12/hashtags/hashtaglist.csv", col_types = cols(col_character(),col_character(),col_double(),col_double(),col_double(),col_double()))

#### merging data ####
tweets_neigh_02 <- merge(neigh_02,tweets_02,by=c("id"))
tweets_neigh_06 <- merge(neigh_06,tweets_06,by=c("id"))
tweets_neigh_09 <- merge(neigh_09,tweets_09,by=c("id"))
tweets_neigh_12 <- merge(neigh_12,tweets_12,by=c("id"))

#### hashtags measures ####
# 02
hashtags_02 <- hashtags_02 %>% mutate(Political_col = ifelse(Political>0,"red","blue")) %>% mutate(Sentiment_col = ifelse(Sentiment>0,"green","purple")) %>% mutate(Alignment_col = ifelse(Alignment>0,"red","blue"))
plot_1 <- ggplot(hashtags_02[0:25,], aes(x=fct_inorder(Id), y=Political, fill=Political_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_blank()) + scale_fill_identity(guide = "none")
plot_2 <- ggplot(hashtags_02[0:25,], aes(x=fct_inorder(Id), y=Sentiment, fill=Sentiment_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_blank()) + scale_fill_identity(guide = "none")
plot_3 <- ggplot(hashtags_02[0:25,], aes(x=fct_inorder(Id), y=Alignment, fill=Alignment_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_text(size = 12, angle = 90)) + scale_fill_identity(guide = "none")
grid.arrange(plot_1,plot_2,plot_3, ncol=1, heights = c(1,1,1.6))
# 06
hashtags_06 <- hashtags_06 %>% mutate(Political_col = ifelse(Political>0,"red","blue")) %>% mutate(Sentiment_col = ifelse(Sentiment>0,"green","purple")) %>% mutate(Alignment_col = ifelse(Alignment>0,"red","blue"))
plot_1 <- ggplot(hashtags_06[0:25,], aes(x=fct_inorder(Id), y=Political, fill=Political_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_blank()) + scale_fill_identity(guide = "none")
plot_2 <- ggplot(hashtags_06[0:25,], aes(x=fct_inorder(Id), y=Sentiment, fill=Sentiment_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_blank()) + scale_fill_identity(guide = "none")
plot_3 <- ggplot(hashtags_06[0:25,], aes(x=fct_inorder(Id), y=Alignment, fill=Alignment_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_text(size = 12, angle = 90)) + scale_fill_identity(guide = "none")
grid.arrange(plot_1,plot_2,plot_3, ncol=1, heights = c(1,1,2.6))
# 09
hashtags_09 <- hashtags_09 %>% mutate(Political_col = ifelse(Political>0,"red","blue")) %>% mutate(Sentiment_col = ifelse(Sentiment>0,"green","purple")) %>% mutate(Alignment_col = ifelse(Alignment>0,"red","blue"))
plot_1 <- ggplot(hashtags_09[0:25,], aes(x=fct_inorder(Id), y=Political, fill=Political_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_blank()) + scale_fill_identity(guide = "none")
plot_2 <- ggplot(hashtags_09[0:25,], aes(x=fct_inorder(Id), y=Sentiment, fill=Sentiment_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_blank()) + scale_fill_identity(guide = "none")
plot_3 <- ggplot(hashtags_09[0:25,], aes(x=fct_inorder(Id), y=Alignment, fill=Alignment_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_text(size = 12, angle = 90)) + scale_fill_identity(guide = "none")
grid.arrange(plot_1,plot_2,plot_3, ncol=1, heights = c(1,1,2))
# 12
hashtags_12 <- hashtags_12 %>% mutate(Political_col = ifelse(Political>0,"red","blue")) %>% mutate(Sentiment_col = ifelse(Sentiment>0,"green","purple")) %>% mutate(Alignment_col = ifelse(Alignment>0,"red","blue"))
plot_1 <- ggplot(hashtags_12[0:25,], aes(x=fct_inorder(Id), y=Political, fill=Political_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_blank()) + scale_fill_identity(guide = "none")
plot_2 <- ggplot(hashtags_12[0:25,], aes(x=fct_inorder(Id), y=Sentiment, fill=Sentiment_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_blank()) + scale_fill_identity(guide = "none")
plot_3 <- ggplot(hashtags_12[0:25,], aes(x=fct_inorder(Id), y=Alignment, fill=Alignment_col)) + geom_bar(stat="Identity") + theme_minimal() + theme(axis.title.x = element_blank(),axis.text.x = element_text(size = 12, angle = 90)) + scale_fill_identity(guide = "none")
grid.arrange(plot_1,plot_2,plot_3, ncol=1, heights = c(1,1,1.8))

#### heat reply political####
# 02
h1 <- hist(filter(tweets_neigh_02, between(political.x,-0.15,0.15))$political.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_02, between(political.x,-0.15,0.15))$political.x, breaks=seq(-0.15,0.15,by=0.015), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_02$political.y, tweets_neigh_02$political.x, n=200, lims=c(-1,1,-0.15,0.15))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(political.x~political.y,data=tweets_neigh_02))
abline(v=median(tweets_neigh_02$political.y),lty="dashed")
abline(h=median(tweets_neigh_02$political.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#06
h1 <- hist(filter(tweets_neigh_06, between(political.x,-0.15,0.15))$political.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_06, between(political.x,-0.15,0.15))$political.x, breaks=seq(-0.15,0.15,by=0.015), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_06$political.y, tweets_neigh_06$political.x, n=200, lims=c(-1,1,-0.15,0.15))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(political.x~political.y,data=tweets_neigh_06))
abline(v=median(tweets_neigh_06$political.y),lty="dashed")
abline(h=median(tweets_neigh_06$political.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#09
h1 <- hist(filter(tweets_neigh_09, between(political.x,-0.15,0.15))$political.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_09, between(political.x,-0.15,0.15))$political.x, breaks=seq(-0.15,0.15,by=0.015), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_09$political.y, tweets_neigh_09$political.x, n=200, lims=c(-1,1,-0.15,0.15))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(political.x~political.y,data=tweets_neigh_09))
abline(v=median(tweets_neigh_09$political.y),lty="dashed")
abline(h=median(tweets_neigh_09$political.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#12
h1 <- hist(filter(tweets_neigh_12, between(political.x,-0.15,0.15))$political.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_12, between(political.x,-0.15,0.15))$political.x, breaks=seq(-0.15,0.15,by=0.015), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_12$political.y, tweets_neigh_12$political.x, n=200, lims=c(-1,1,-0.15,0.15))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(political.x~political.y,data=tweets_neigh_12))
abline(v=median(tweets_neigh_12$political.y),lty="dashed")
abline(h=median(tweets_neigh_12$political.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)

#### heat reply sentiment####
# 02
h1 <- hist(filter(tweets_neigh_02, between(sentiment.x,-0.5,0.5))$sentiment.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_02, between(sentiment.x,-0.5,0.5))$sentiment.x, breaks=seq(-0.5,0.5,by=0.05), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_02$sentiment.y, tweets_neigh_02$sentiment.x, n=200, lims=c(-1,1,-0.5,0.5))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment.x~sentiment.y,data=tweets_neigh_02))
abline(v=median(tweets_neigh_02$sentiment.y),lty="dashed")
abline(h=median(tweets_neigh_02$sentiment.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#06
h1 <- hist(filter(tweets_neigh_06, between(sentiment.x,-0.5,0.5))$sentiment.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_06, between(sentiment.x,-0.5,0.5))$sentiment.x, breaks=seq(-0.5,0.5,by=0.05), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_06$sentiment.y, tweets_neigh_06$sentiment.x, n=200, lims=c(-1,1,-0.5,0.5))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment.x~sentiment.y,data=tweets_neigh_06))
abline(v=median(tweets_neigh_06$sentiment.y),lty="dashed")
abline(h=median(tweets_neigh_06$sentiment.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#09
h1 <- hist(filter(tweets_neigh_09, between(sentiment.x,-0.5,0.5))$sentiment.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_09, between(sentiment.x,-0.5,0.5))$sentiment.x, breaks=seq(-0.5,0.5,by=0.05), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_09$sentiment.y, tweets_neigh_09$sentiment.x, n=200, lims=c(-1,1,-0.5,0.5))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment.x~sentiment.y,data=tweets_neigh_09))
abline(v=median(tweets_neigh_09$sentiment.y),lty="dashed")
abline(h=median(tweets_neigh_09$sentiment.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#12
h1 <- hist(filter(tweets_neigh_12, between(sentiment.x,-0.5,0.5))$sentiment.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_12, between(sentiment.x,-0.5,0.5))$sentiment.x, breaks=seq(-0.5,0.5,by=0.05), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_12$sentiment.y, tweets_neigh_12$sentiment.x, n=200, lims=c(-1,1,-0.5,0.5))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment.x~sentiment.y,data=tweets_neigh_12))
abline(v=median(tweets_neigh_12$sentiment.y),lty="dashed")
abline(h=median(tweets_neigh_12$sentiment.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)

#### heat reply alignment####
# 02
h1 <- hist(filter(tweets_neigh_02, between(alignment.x,-0.05,0.05))$alignment.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_02, between(alignment.x,-0.05,0.05))$alignment.x, breaks=seq(-0.05,0.05,by=0.005), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_02$alignment.y, tweets_neigh_02$alignment.x, n=200, lims=c(-1,1,-0.05,0.05))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(alignment.x~alignment.y,data=tweets_neigh_02))
abline(v=median(tweets_neigh_02$alignment.y),lty="dashed")
abline(h=median(tweets_neigh_02$alignment.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#06
h1 <- hist(filter(tweets_neigh_06, between(alignment.x,-0.05,0.05))$alignment.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_06, between(alignment.x,-0.05,0.05))$alignment.x, breaks=seq(-0.05,0.05,by=0.005), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_06$alignment.y, tweets_neigh_06$alignment.x, n=200, lims=c(-1,1,-0.05,0.05))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(alignment.x~alignment.y,data=tweets_neigh_06))
abline(v=median(tweets_neigh_06$alignment.y),lty="dashed")
abline(h=median(tweets_neigh_06$alignment.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#09
h1 <- hist(filter(tweets_neigh_09, between(alignment.x,-0.05,0.05))$alignment.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_09, between(alignment.x,-0.05,0.05))$alignment.x, breaks=seq(-0.05,0.05,by=0.005), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_09$alignment.y, tweets_neigh_09$alignment.x, n=200, lims=c(-1,1,-0.05,0.05))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(alignment.x~alignment.y,data=tweets_neigh_09))
abline(v=median(tweets_neigh_09$alignment.y),lty="dashed")
abline(h=median(tweets_neigh_09$alignment.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#12
h1 <- hist(filter(tweets_neigh_12, between(alignment.x,-0.05,0.05))$alignment.y, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_neigh_12, between(alignment.x,-0.05,0.05))$alignment.x, breaks=seq(-0.05,0.05,by=0.005), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_neigh_12$alignment.y, tweets_neigh_12$alignment.x, n=200, lims=c(-1,1,-0.05,0.05))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(alignment.x~alignment.y,data=tweets_neigh_12))
abline(v=median(tweets_neigh_12$alignment.y),lty="dashed")
abline(h=median(tweets_neigh_12$alignment.x),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)

#### heat political vs sentiment####
# 02
h1 <- hist(tweets_02$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(tweets_02$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_02$political, tweets_02$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~political,data=tweets_02))
abline(v=median(tweets_02$political),lty="dashed")
abline(h=median(tweets_02$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#06
h1 <- hist(tweets_06$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(tweets_06$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_06$political, tweets_06$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~political,data=tweets_06))
abline(v=median(tweets_06$political),lty="dashed")
abline(h=median(tweets_06$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#09
h1 <- hist(tweets_09$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(tweets_09$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_09$political, tweets_09$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~political,data=tweets_09))
abline(v=median(tweets_09$political),lty="dashed")
abline(h=median(tweets_09$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#12
h1 <- hist(tweets_12$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(tweets_12$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(tweets_12$political, tweets_12$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~political,data=tweets_12))
abline(v=median(tweets_12$political),lty="dashed")
abline(h=median(tweets_12$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)

#### heat political vs sentiment filtered####
# 02
h1 <- hist(filter(tweets_02, !between(sentiment,-0.05,0.05))$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_02, !between(sentiment,-0.05,0.05))$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_02, !between(sentiment,-0.05,0.05))$political, filter(tweets_02, !between(sentiment,-0.05,0.05))$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~political,data=filter(tweets_02, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_02, !between(sentiment,-0.05,0.05))$political),lty="dashed")
abline(h=median(filter(tweets_02, !between(sentiment,-0.05,0.05))$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#06
h1 <- hist(filter(tweets_06, !between(sentiment,-0.05,0.05))$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_06, !between(sentiment,-0.05,0.05))$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_06, !between(sentiment,-0.05,0.05))$political, filter(tweets_06, !between(sentiment,-0.05,0.05))$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~political,data=filter(tweets_06, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_06, !between(sentiment,-0.05,0.05))$political),lty="dashed")
abline(h=median(filter(tweets_06, !between(sentiment,-0.05,0.05))$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#09
h1 <- hist(filter(tweets_09, !between(sentiment,-0.05,0.05))$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_09, !between(sentiment,-0.05,0.05))$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_09, !between(sentiment,-0.05,0.05))$political, filter(tweets_09, !between(sentiment,-0.05,0.05))$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~political,data=filter(tweets_09, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_09, !between(sentiment,-0.05,0.05))$political),lty="dashed")
abline(h=median(filter(tweets_09, !between(sentiment,-0.05,0.05))$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#12
h1 <- hist(filter(tweets_12, !between(sentiment,-0.05,0.05))$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_12, !between(sentiment,-0.05,0.05))$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_12, !between(sentiment,-0.05,0.05))$political, filter(tweets_12, !between(sentiment,-0.05,0.05))$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~political,data=filter(tweets_12, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_12, !between(sentiment,-0.05,0.05))$political),lty="dashed")
abline(h=median(filter(tweets_12, !between(sentiment,-0.05,0.05))$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)

#### heat political vs alignment filtered####
# 02
h1 <- hist(filter(tweets_02, !between(sentiment,-0.05,0.05))$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_02, !between(sentiment,-0.05,0.05))$alignment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_02, !between(sentiment,-0.05,0.05))$political, filter(tweets_02, !between(sentiment,-0.05,0.05))$alignment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(alignment~political,data=filter(tweets_02, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_02, !between(sentiment,-0.05,0.05))$political),lty="dashed")
abline(h=median(filter(tweets_02, !between(sentiment,-0.05,0.05))$alignment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#06
h1 <- hist(filter(tweets_06, !between(sentiment,-0.05,0.05))$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_06, !between(sentiment,-0.05,0.05))$alignment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_06, !between(sentiment,-0.05,0.05))$political, filter(tweets_06, !between(sentiment,-0.05,0.05))$alignment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(alignment~political,data=filter(tweets_06, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_06, !between(sentiment,-0.05,0.05))$political),lty="dashed")
abline(h=median(filter(tweets_06, !between(sentiment,-0.05,0.05))$alignment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#09
h1 <- hist(filter(tweets_09, !between(sentiment,-0.05,0.05))$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_09, !between(sentiment,-0.05,0.05))$alignment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_09, !between(sentiment,-0.05,0.05))$political, filter(tweets_09, !between(sentiment,-0.05,0.05))$alignment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(alignment~political,data=filter(tweets_09, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_09, !between(sentiment,-0.05,0.05))$political),lty="dashed")
abline(h=median(filter(tweets_09, !between(sentiment,-0.05,0.05))$alignment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#12
h1 <- hist(filter(tweets_12, !between(sentiment,-0.05,0.05))$political, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_12, !between(sentiment,-0.05,0.05))$alignment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_12, !between(sentiment,-0.05,0.05))$political, filter(tweets_12, !between(sentiment,-0.05,0.05))$alignment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(alignment~political,data=filter(tweets_12, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_12, !between(sentiment,-0.05,0.05))$political),lty="dashed")
abline(h=median(filter(tweets_12, !between(sentiment,-0.05,0.05))$alignment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)




#### heat alignment vs sentiment filtered####
# 02
h1 <- hist(filter(tweets_02, !between(sentiment,-0.05,0.05))$alignment, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_02, !between(sentiment,-0.05,0.05))$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_02, !between(sentiment,-0.05,0.05))$alignment, filter(tweets_02, !between(sentiment,-0.05,0.05))$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~alignment,data=filter(tweets_02, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_02, !between(sentiment,-0.05,0.05))$alignment),lty="dashed")
abline(h=median(filter(tweets_02, !between(sentiment,-0.05,0.05))$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#06
h1 <- hist(filter(tweets_06, !between(sentiment,-0.05,0.05))$alignment, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_06, !between(sentiment,-0.05,0.05))$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_06, !between(sentiment,-0.05,0.05))$alignment, filter(tweets_06, !between(sentiment,-0.05,0.05))$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~alignment,data=filter(tweets_06, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_06, !between(sentiment,-0.05,0.05))$alignment),lty="dashed")
abline(h=median(filter(tweets_06, !between(sentiment,-0.05,0.05))$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#09
h1 <- hist(filter(tweets_09, !between(sentiment,-0.05,0.05))$alignment, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_09, !between(sentiment,-0.05,0.05))$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_09, !between(sentiment,-0.05,0.05))$alignment, filter(tweets_09, !between(sentiment,-0.05,0.05))$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~alignment,data=filter(tweets_09, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_09, !between(sentiment,-0.05,0.05))$alignment),lty="dashed")
abline(h=median(filter(tweets_09, !between(sentiment,-0.05,0.05))$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)
#12
h1 <- hist(filter(tweets_12, !between(sentiment,-0.05,0.05))$alignment, breaks=seq(-1,1,by=0.1), plot=F)
h2 <- hist(filter(tweets_12, !between(sentiment,-0.05,0.05))$sentiment, breaks=seq(-1,1,by=0.1), plot=F)
top <- max(h1$counts, h2$counts)
k <- kde2d(filter(tweets_12, !between(sentiment,-0.05,0.05))$alignment, filter(tweets_12, !between(sentiment,-0.05,0.05))$sentiment, n=200, lims=c(-1,1,-1,1))
oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k) #plot the image
abline(lm(sentiment~alignment,data=filter(tweets_12, !between(sentiment,-0.05,0.05))))
abline(v=median(filter(tweets_12, !between(sentiment,-0.05,0.05))$alignment),lty="dashed")
abline(h=median(filter(tweets_12, !between(sentiment,-0.05,0.05))$sentiment),lty="dashed")
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)

#### density political over time ####
par(mfrow=c(1,1))
d_02 <- density(tweets_02$political)
d_06 <- density(tweets_06$political)
d_09 <- density(tweets_09$political)
d_12 <- density(tweets_12$political)
plot(d_02, col="red", ylim=c(0,1.2), main="")
lines(d_06, col="blue")
lines(d_09, col="green")
lines(d_12)
abline(v=mean(tweets_02$political), col="red", lty="dashed")
abline(v=mean(tweets_06$political), col="blue", lty="dashed")
abline(v=mean(tweets_09$political), col="green", lty="dashed")
abline(v=mean(tweets_12$political), lty="dashed")
legend(-1.31, 1.248, legend=c("February", "June", "September", "December"),
       col=c("red", "blue", "green", "black"), lty=1, cex=0.8)

#### density sentiment over time ####
par(mfrow=c(1,1))
d_02 <- density(tweets_02$sentiment)
d_06 <- density(tweets_06$sentiment)
d_09 <- density(tweets_09$sentiment)
d_12 <- density(tweets_12$sentiment)
plot(d_02, col="red", ylim=c(0,2.4), main="")
lines(d_06, col="blue")
lines(d_09, col="green")
lines(d_12)
abline(v=mean(tweets_02$sentiment), col="red", lty="dashed")
abline(v=mean(tweets_06$sentiment), col="blue", lty="dashed")
abline(v=mean(tweets_09$sentiment), col="green", lty="dashed")
abline(v=mean(tweets_12$sentiment), lty="dashed")
legend(-1.27, 2.495, legend=c("February", "June", "September", "December"),
       col=c("red", "blue", "green", "black"), lty=1, cex=0.8)

#### density alignment over time ####
par(mfrow=c(1,1))
d_02 <- density(tweets_02$alignment)
d_06 <- density(tweets_06$alignment)
d_09 <- density(tweets_09$alignment)
d_12 <- density(tweets_12$alignment)
plot(d_02, col="red", ylim=c(0,8), main="")
lines(d_06, col="blue")
lines(d_09, col="green")
lines(d_12)
abline(v=mean(tweets_02$alignment), col="red", lty="dashed")
abline(v=mean(tweets_06$alignment), col="blue", lty="dashed")
abline(v=mean(tweets_09$alignment), col="green", lty="dashed")
abline(v=mean(tweets_12$alignment), lty="dashed")
legend(-1.12, 8.32, legend=c("February", "June", "September", "December"),
       col=c("red", "blue", "green", "black"), lty=1, cex=0.8)